### PR TITLE
fix: eslint should replace dashes for underscore 

### PR DESCRIPTION
**Pull request by hanoii**
Same as symlink-project

### CODE REVIEW

**Comment by claudiu-cristea** [comment]
@weitzman this bug is breaking with modules having underscore(s) in name. Could you, please, cut a release to benefit for the fix?

**Comment by rfay** [comment]
@claudiu-cristea Are you using a recent DDEV? Since v1.23.4, DDEV automatically uses dashes for the project name.

**Comment by hanoii** [comment]
@rfay I think the problem is a different one, he meant that with the project using dashes, the eslint command failed because of that, as the module is with underscores, so we are changing it to underscores now.

He just need a new release of the addon.

**Comment by hanoii** [comment]
It's what this PR fixes

**Comment by claudiu-cristea** [comment]
Anyway, I don't think is solution is 100% safe. What if the module name is `just_a_module` but the developer decides to name the project `my-proj`? The whole logic goes away

**Comment by hanoii** [comment]
I am pretty sure nothing will hgappen. The symlink command will symlink your modules files into a `my_proj` directory and will work the same 

https://www.drupal.org/docs/develop/creating-modules/naming-and-placing-your-drupal-module#s-create-a-folder-for-your-module

> Note that it is not necessary to use the same name for your module's folder as your machine name. You could, for example, use the folder name HelloWorld instead. However, you must remember to use the machine name programmatically within your module's code and filenames.

**Pull request merged**
