### PR TITLE
[docs] DDEV project type

### PR DESCRIPTION
**Pull request by tyler36**
This PR addresses #6. 

It is a draft to allow others to discuss solutions and wording.

### CODE REVIEW

**Comment by weitzman** [comment]
LGTM. Maybe we start with this and then allow 'php' project to see our commands if people keep tripping up here. I'll leave this open for another day or two fir comments

**Comment by kreynen** [comment]
I don't think you need to explain how to edit the config.yml if the correct config is done initially. I proposed a different change in https://github.com/ddev/ddev-drupal-contrib/pull/9

**Comment by tyler36** [comment]
Perhaps we can include #9 for instructions but move this down to a troubleshooting section?

**Comment by weitzman** [comment]
Good idea.

**Comment by tyler36** [comment]
OK. I've simplified this and pushed it to the bottom.
This should allow the information to be present without conflicting with #9 .

**Pull request merged**
